global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@conceptusveritas.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password' # Replace with actual password or use secrets management
  smtp_require_tls: true

templates:
  - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-email'
  routes:
    - match:
        severity: critical
      receiver: 'team-pager'
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: 'team-email'
      repeat_interval: 12h

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
  - name: 'team-email'
    email_configs:
      - to: 'team@conceptusveritas.com'
        send_resolved: true
        html: '{{ template "email.default.html" . }}'
        headers:
          subject: '{{ template "email.default.subject" . }}'

  - name: 'team-pager'
    email_configs:
      - to: 'pager@conceptusveritas.com'
        send_resolved: true
    webhook_configs:
      - url: 'http://pagerduty-integration:8080/'
        send_resolved: true

  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX' # Replace with actual Slack webhook URL
        channel: '#monitoring-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        title_link: 'http://grafana:3000/d/monitoring'
        footer: 'Conceptus Veritas Monitoring'
